name: Weekly

on:
  schedule:
    - cron: '59 6 * * 4'

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ['1.60', stable]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo build --workspace
